# Generated by Django 5.1.1 on 2025-06-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPNServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_user', models.IntegerField(default=0, help_text='Сколько пользоватлей на сервере?')),
                ('xui_host', models.CharField(blank=True, help_text='hsot', max_length=500, null=True)),
                ('xui_username', models.CharField(blank=True, help_text='xui_username', max_length=500, null=True)),
                ('xui_password', models.CharField(blank=True, help_text='xui_password', max_length=500, null=True)),
                ('xui_external_ip', models.CharField(blank=True, help_text='xui_external_ip', max_length=500, null=True)),
                ('main_remark', models.CharField(default='Go%20Play%20Donate%20VPN', help_text='main_remark', max_length=500)),
                ('port_client', models.IntegerField(default=443, help_text='port_client')),
                ('inbound_id', models.IntegerField(default=1, help_text='inbound_id')),
            ],
        ),
    ]
