# Generated by Django 5.1.1 on 2025-06-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrey_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnserver',
            name='main_remark',
            field=models.CharField(default='W%20VPN', help_text='main_remark', max_length=500),
        ),
    ]
