# Generated by Django 5.1.1 on 2025-01-17 20:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('current_state', models.CharField(default=None, max_length=110, unique=True, verbose_name='К какому состоянию привязана?')),
                ('next_state', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ссылка на состояние при вводе')),
                ('anyway_link', models.CharField(blank=True, help_text='На какое состояние пебрасывает пользователя', max_length=110, null=True, unique=True)),
                ('handler', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Имя функции обработчика')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True, verbose_name='ID Telegram')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Фамилия пользователя')),
                ('username', models.CharField(blank=True, max_length=250, null=True, verbose_name='Username пользователя')),
                ('language', models.CharField(blank=True, max_length=250, null=True, verbose_name='Язык пользователя')),
                ('premium', models.BooleanField(blank=True, default=False, null=True, verbose_name='Имеет ли пользователь премиум-аккаунт')),
                ('state', models.CharField(help_text='Состояние', max_length=255)),
                ('last_message_id', models.BigIntegerField(blank=True, help_text='ID последнего отправленного сообщения с кнопками', null=True)),
                ('last_input_message_id', models.BigIntegerField(blank=True, help_text='ID последнего отправленного сообщения без кнопок', null=True)),
            ],
            options={
                'verbose_name': 'Пользователь бота',
                'verbose_name_plural': 'Пользователи бота',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.TextField(verbose_name='id заявки')),
                ('status', models.CharField(max_length=255, verbose_name='статус оплаты')),
                ('user_id', models.CharField(max_length=255, verbose_name='id пользоователя')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Оплату',
                'verbose_name_plural': 'Оплаты',
            },
        ),
        migrations.CreateModel(
            name='TelegramBotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=100)),
                ('is_activ', models.BooleanField(default=False, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Токен',
                'verbose_name_plural': 'Токены',
            },
        ),
        migrations.CreateModel(
            name='Text_Castom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField(verbose_name='Привязка')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Редактор текстовок',
                'verbose_name_plural': 'Редактор текстовок',
            },
        ),
        migrations.CreateModel(
            name='Bot_Commands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст команды')),
                ('trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_commands', to='bot.bot_message', verbose_name='Связанное сообщение')),
            ],
            options={
                'verbose_name': 'Команду / reply кнопку',
                'verbose_name_plural': 'Команды / reply кнопки',
            },
        ),
        migrations.CreateModel(
            name='Bot_Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст кнопки')),
                ('data', models.CharField(default='', max_length=255, verbose_name='Данные')),
                ('message_trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_triggered', to='bot.bot_message', verbose_name='Связанное сообщение')),
            ],
            options={
                'verbose_name': 'Кнопку',
                'verbose_name_plural': 'Кнопки',
            },
        ),
    ]
