# Generated by Django 5.1.1 on 2025-01-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='language_chooce',
            field=models.CharField(blank=True, choices=[('ru', 'ru'), ('en', 'en')], max_length=4, null=True, verbose_name='Выбор языка'),
        ),
    ]
