# Generated by Django 5.1.1 on 2025-01-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_botuser_language_chooce'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='balance_ice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Замороженный баланс'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='language_chooce',
            field=models.CharField(blank=True, choices=[('ru', 'ru'), ('en', 'en')], default='ru', max_length=4, null=True, verbose_name='Выбор языка'),
        ),
    ]
