# Generated by Django 5.1.1 on 2025-01-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_botuser_balance_botuser_balance_ice_botuser_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot_button',
            name='type_btn',
            field=models.CharField(blank=True, choices=[('Inline', 'Inline'), ('Reply', 'Reply')], max_length=20, null=True, verbose_name='Тип кнопки'),
        ),
    ]
