# Generated by Django 5.1.1 on 2025-01-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_bot_button_type_btn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot_button',
            name='type_btn',
            field=models.CharField(blank=True, choices=[('Inline', 'Inline'), ('Reply', 'Reply')], default='Inline', max_length=20, null=True, verbose_name='Тип кнопки'),
        ),
    ]
