# Generated by Django 5.1.1 on 2025-01-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_bot_button_type_btn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Тег'),
        ),
    ]
