# Generated by Django 5.1.1 on 2025-01-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_botuser_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='balance_ice',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='tag',
        ),
        migrations.AddField(
            model_name='botuser',
            name='name_key',
            field=models.CharField(blank=True, default='#W%20VPN', max_length=255, null=True, verbose_name='Имя ключа'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='outline_key',
            field=models.TextField(blank=True, null=True, verbose_name='Ключ для Outline'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='subscription',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Подписка на VPN'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='subscription_date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания подписки'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='subscription_date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала подписки'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='trial_period',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Пробный период 1 день'),
        ),
    ]
