# Generated by Django 5.1.1 on 2025-01-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_remove_botuser_balance_remove_botuser_balance_ice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_castom',
            name='hint',
            field=models.TextField(blank=True, null=True, verbose_name='Подсказка'),
        ),
    ]
