# Generated by Django 5.1.1 on 2025-01-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_text_castom_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot_button',
            name='type_data',
            field=models.CharField(blank=True, choices=[('data', 'data'), ('url', 'url')], default='data', max_length=20, null=True, verbose_name='Тип данных'),
        ),
    ]
