# Generated by Django 5.1.1 on 2025-01-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_bot_button_type_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена'),
        ),
    ]
