# Generated by Django 5.1.1 on 2025-01-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_payment_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='key_id',
            field=models.BigIntegerField(blank=True, help_text='Id ключа', null=True),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='name_key',
            field=models.CharField(blank=True, default='#W%20VPN', help_text='Имя ключа', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='outline_key',
            field=models.TextField(blank=True, help_text='Ключ для Outline', null=True),
        ),
    ]
