# Generated by Django 5.1.1 on 2025-01-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_botuser_key_id_alter_botuser_name_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='notif_subscribe_close',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Уведовление о окончании подписки'),
        ),
    ]
