# Generated by Django 5.1.1 on 2025-06-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_botuser_notif_subscribe_close'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='outline_key',
        ),
        migrations.AddField(
            model_name='botuser',
            name='vpn_key',
            field=models.TextField(blank=True, help_text='Ключ для vpn', null=True),
        ),
    ]
