# Generated by Django 5.1.1 on 2025-06-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_bot_button_button_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='limit_ip',
            field=models.IntegerField(blank=True, null=True, verbose_name='id пользоователя'),
        ),
        migrations.AlterField(
            model_name='bot_button',
            name='button_position',
            field=models.CharField(blank=True, choices=[('Первый ряд', [('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')]), ('Второй ряд', [('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')]), ('Третий ряд', [('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')]), ('Четвертый ряд', [('13', '13'), ('14', '14'), ('15', '15'), ('16', '16')]), ('Пятый ряд', [('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')])], max_length=3, null=True, verbose_name='Позиция кнопки'),
        ),
    ]
