# Generated by Django 5.1.1 on 2025-06-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_payment_limit_ip_alter_bot_button_button_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='period',
            field=models.IntegerField(blank=True, null=True, verbose_name='Срок'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='limit_ip',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во устройств'),
        ),
    ]
