# Generated by Django 5.1.1 on 2025-09-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_payment_period_alter_payment_limit_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='referal_url',
            field=models.CharField(blank=True, help_text='Реферальная ссылка', max_length=255, null=True),
        ),
    ]
