# Generated by Django 5.1.1 on 2025-09-18 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_referal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReferal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('referal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bot.referal', verbose_name='Реферал')),
            ],
        ),
    ]
