# Generated by Django 5.1.1 on 2025-11-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_paymentreferal'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='server_chooce',
            field=models.IntegerField(blank=True, help_text='Выбранный сервер', null=True),
        ),
    ]
