# Generated by Django 5.1.1 on 2026-02-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_botuser_server_chooce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot_button',
            name='type_data',
            field=models.CharField(blank=True, choices=[('data', 'data'), ('url', 'url'), ('web_app', 'web_app')], default='data', max_length=20, null=True, verbose_name='Тип данных'),
        ),
    ]
