# Generated by Django 5.1.1 on 2026-02-19 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_alter_bot_button_type_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='trial_period',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Пробный период'),
        ),
    ]
