# Generated by Django 5.1.1 on 2026-03-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_botuser_created_at_alter_botuser_trial_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='notif_1d',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botuser',
            name='notif_1h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botuser',
            name='notif_3d',
            field=models.BooleanField(default=False),
        ),
    ]
