# Generated by Django 5.1.1 on 2026-03-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_botuser_notif_1d_botuser_notif_1h_botuser_notif_3d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='notif_1d',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Уведомление за 1дн'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='notif_1h',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Уведомление за 1ч'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='notif_3d',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Уведомление за 3дн'),
        ),
    ]
